name: practica_github_actions
on:
  push:
    branches:
      - "master"
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -D
      - run: npm run lint

  Cypress_job:
    runs-on: ubuntu-latest
    needs: Linter_job
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        id: cypress
        continue-on-error: true
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"
          record: true
      - run: echo ${{ steps.cypress.outcome }} > results.txt
      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: ./results.txt

  Add_badge_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: results
      - run: cat results.txt
