name: practica_github_actions
on:
  push:
    branches:
      - "master"
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -D
      - run: npm run lint

  Cypress_job:
    runs-on: ubuntu-latest
    needs: Linter_job
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        id: cypress
        continue-on-error: true
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"
          quiet: true
      - run: echo ${{ steps.cypress.outcome }} > results.txt
      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: ./results.txt

  Add_badge_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.SSH_KEY}}
          ssh-strict: false
      - uses: actions/download-artifact@v3
        with:
          name: results
      - run: echo "::set-output name=cypress_outcome::$(cat results.txt)"
        id: save_results
      - uses: ./.github/actions/badge
        with:
          cypress_results: ${{ steps.save_results.outputs.cypress_outcome }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Workflow practica_github_actions"
          message: "Cypress results updated [skip actions]"
          push: true

  Deploy_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}

  Notification_job:
    runs-on: ubuntu-latest
    needs: [Linter_job, Cypress_job, Add_badge_job, Deploy_job]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: results
      - run: echo "::set-output name=cypress_outcome::$(cat results.txt)"
        id: save_results
      - uses: ./.github/actions/email
        with:
          linter_job: ${{ needs.Linter_job.result }}
          cypress_job: ${{ steps.save_results.outputs.cypress_outcome }}
          add_badge_job: ${{ needs.Add_badge_job.result }}
          deploy_job: ${{ needs.Deploy_job.result }}
          email: ${{ secrets.EMAIL }}
          mailtrap_user: ${{ secrets.MAILTRAP_USER }}
          mailtrap_pass: ${{ secrets.MAILTRAP_PASS }}
