name: practica_github_actions
on:
  push:
    branches:
      - "master"
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -D
      - run: npm run lint

  Cypress_job:
    runs-on: ubuntu-latest
    needs: Linter_job
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          working-directory: ./result.txt
          quiet: true
      - run: ls -la
